
server:
  port: 8099
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/bigbin?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username : bigbin
    password : bigbin
    driverClassName : com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
  #redis配置
  redis:
      cluster:
        nodes: 127.0.0.1:6379
      expireSeconds: 120
      commandTimeout: 10000  #redis操作的超时时间
      jedis:
        pool:
          maxActive: 5000 #最大连接数
          maxIdle: 30 #最大空闲连接数
          minIdle: 5 #最小空闲连接数
          maxWait: 3000
      messages:
          basename: messages, index
      cloud:
        kubernetes:
          enabled: false

logging:
  config: classpath:log4j2.xml
  #指定日志的等级
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

#跨域支持
web.cors:
  enabled: true
  allowCredentials: true
  allowedOrigins:
    - '*'
  allowedHeaders:
    - '*'
  allowedMethods:
    - '*'